### ISSUE TITLE
Error should implement std::error::Error trait

### ISSUE THREAD

**Issue by nazar-pc** [iddm/thread-priority#37]
Right now it is a bit problematic in some contexts because of that. `thiserror` crate can be used to derive it conveniently.

**Comment by iddm** [comment]
Hi @nazar-pc and thank you for your question. I think this has already been done, I have just forgotten to publish the new version.

**Comment by iddm** [comment]
The relevant changes should be here: https://crates.io/crates/thread-priority/0.16.0

Please reopen this issue if it is not. Have a great day!
